[package]
name = "jackalopefs-server"
description = "jackalopefs server: exports a directory over QUIC"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true


[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
humantime = { workspace = true }
jackalopefs-perf = { workspace = true }
jackalopefs-proto = { workspace = true }
libc = { workspace = true }
nix = { workspace = true, features = ["resource"] }
notify = { workspace = true }
parking_lot = { workspace = true }
quinn = { workspace = true }
rand = { workspace = true }
rcgen = { workspace = true }
rustls = { workspace = true }
subtle = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
